<%
out.print("<nav class='container-xxl navbar navbar-expand-lg bg-body-tertiary'>");
out.print("  <div class='container-fluid'>");
out.print("    <div class='collapse navbar-collapse' id='navbarSupportedContent'>");
out.print("      <ul class='navbar-nav me-auto mb-2 mb-lg-0'>");
out.print("        <li class='nav-item'>");
out.print("        		<a class='nav-link active' aria-current='page' href='./index.jsp?'>Home</a>");
out.print("        </li>");
out.print("        <li class='nav-item dropdown'>");
out.print("          	<a class='nav-link dropdown-toggle' href='#' role='button' data-bs-toggle='dropdown' aria-expanded='false'>");
out.print("            		Contatos");
out.print("          	</a>");
out.print("          	<ul class='dropdown-menu'>");
out.print("            		<li><a class='dropdown-item' href='./cadastroContato.jsp'>Cadastrar contato</a></li>");
out.print("            		<li><a class='dropdown-item' href='./consultaContato.jsp'>Consultar contato</a></li>");
out.print("          	</ul>");
out.print("        </li>");
out.print("        <li class='nav-item dropdown'>");
out.print("        		<a class='nav-link dropdown-toggle' href='#' role='button' data-bs-toggle='dropdown' aria-expanded='false'>");
out.print("            		Locais");
out.print("          	</a>");
out.print("          	<ul class='dropdown-menu'>");
out.print("            		<li><a class='dropdown-item' href='./cadastroLocal.jsp'>Cadastrar local</a></li>");
out.print("            		<li><a class='dropdown-item' href='./consultaLocal.jsp'>Consultar local</a></li>");
out.print("          	</ul>");
out.print("        </li>");
out.print("        <li class='nav-item dropdown'>");
out.print("        		<a class='nav-link dropdown-toggle' href='#' role='button' data-bs-toggle='dropdown' aria-expanded='false'>");
out.print("            		Compromissos");
out.print("          	</a>");
out.print("          	<ul class='dropdown-menu'>");
out.print("            		<li><a class='dropdown-item' href='#'>Cadastrar compromisso</a></li>");
out.print("            		<li><a class='dropdown-item' href='#'>Consultar compromissos</a></li>");
out.print("          	</ul>");
out.print("        </li>");
out.print("      </ul>");
out.print("    </div>");
out.print("  </div>");
out.print("</nav>");
out.print("<script src='https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js' integrity='sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r' crossorigin='anonymous'></script>");
out.print("<script src='https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js' integrity='sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+' crossorigin='anonymous'></script>");
%> 